uagbot_build:
  image: docker:20
  stage: build
  services:
    - docker:20-dind
  variables:
    BUILD_CONTEXT: active/unnamed-discord-bot
    CONTAINER_IDENTIFIER: zuedev/monorepo/unnamed-discord-bot
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CONTAINER_IDENTIFIER:$CI_COMMIT_SHA -t $CI_REGISTRY/$CONTAINER_IDENTIFIER:latest ./$BUILD_CONTEXT
    - docker push $CI_REGISTRY/$CONTAINER_IDENTIFIER --all-tags
  only:
    changes:
      - /active/unnamed-discord-bot/**/*
